"""Add daily_cognitive_budget to User

Revision ID: abd375d0e4c3
Revises: b6370fd61ecb
Create Date: 2026-01-27 13:33:26.059134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd375d0e4c3'
down_revision = 'b6370fd61ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_cognitive_budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_cognitive_budget')

    # ### end Alembic commands ###
