"""Add Rule Engine fields to ScheduleBlock

Revision ID: b6370fd61ecb
Revises: 0b5c1643d0bc
Create Date: 2026-01-27 11:09:36.981993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6370fd61ecb'
down_revision = '0b5c1643d0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refinement_reason', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('academic_citation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('logic_explanation', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_block', schema=None) as batch_op:
        batch_op.drop_column('logic_explanation')
        batch_op.drop_column('academic_citation')
        batch_op.drop_column('refinement_reason')

    # ### end Alembic commands ###
