"""add session_insight to study_session

Revision ID: 4e2d35e6af62
Revises: c7551a00ed54
Create Date: 2026-02-25 08:20:18.217704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2d35e6af62'
down_revision = 'c7551a00ed54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_insight', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_column('session_insight')

    # ### end Alembic commands ###
