"""Add created_at timestamps

Revision ID: 7a5d9d4f4b81
Revises: dd177a431e4a
Create Date: 2026-01-31 17:23:51.793027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5d9d4f4b81'
down_revision = 'dd177a431e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_column('pause_duration')

    with op.batch_alter_table('system_alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_alert', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pause_duration', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('schedule_block', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
