"""Fix user_courses duplication

Revision ID: 88b2448a5523
Revises: abd375d0e4c3
Create Date: 2026-01-27 13:49:13.071424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b2448a5523'
down_revision = 'abd375d0e4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    with op.batch_alter_table('schedule_block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    with op.batch_alter_table('user_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_courses', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    with op.batch_alter_table('schedule_block', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
