"""add_annotation_to_notes

Revision ID: 96161c550b15
Revises: f46c86d045ef
Create Date: 2026-05-19 08:37:03.837577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96161c550b15'
down_revision = 'f46c86d045ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('annotation')

    # ### end Alembic commands ###
