"""add_token_to_pending_registration

Revision ID: 9d4479139190
Revises: e6e52f39f398
Create Date: 2026-05-18 06:26:40.365545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4479139190'
down_revision = 'e6e52f39f398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
