"""Add pause_duration to StudySession

Revision ID: dd177a431e4a
Revises: 88b2448a5523
Create Date: 2026-01-27 14:22:58.321868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd177a431e4a'
down_revision = '88b2448a5523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pause_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_column('pause_duration')

    # ### end Alembic commands ###
