"""update_file_type_non_nullable

Revision ID: f46c86d045ef
Revises: 9d4479139190
Create Date: 2026-05-19 02:42:10.036426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46c86d045ef'
down_revision = '9d4479139190'
branch_labels = None
depends_on = None


def upgrade():
    # First, backfill any existing NULL file_type values to 'pdf'
    op.execute("UPDATE note SET file_type = 'pdf' WHERE file_type IS NULL")

    # Then apply the schema change
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False,
               existing_server_default=None,
               server_default='pdf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
